# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 初始页
    url: /
    weight: 10
  - name: 问题
    url: /questions/
    weight: 20
  - name: FAQ
    url: /faq/
    weight: 30
  - name: 类型
    url: /#categories
    weight: 40
  - name: 潮流
    url: /#trending
    weight: 50
